# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magnet.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='magnet.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cmagnet.proto\" \n\rMagnetRequest\x12\x0f\n\x07imdb_id\x18\x01 \x01(\t\"\x1a\n\x0bMagnetReply\x12\x0b\n\x03url\x18\x01 \x01(\t25\n\x06Magnet\x12+\n\tGetMagnet\x12\x0e.MagnetRequest\x1a\x0c.MagnetReply\"\x00\x62\x06proto3'
)




_MAGNETREQUEST = _descriptor.Descriptor(
  name='MagnetRequest',
  full_name='MagnetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imdb_id', full_name='MagnetRequest.imdb_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=48,
)


_MAGNETREPLY = _descriptor.Descriptor(
  name='MagnetReply',
  full_name='MagnetReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='MagnetReply.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['MagnetRequest'] = _MAGNETREQUEST
DESCRIPTOR.message_types_by_name['MagnetReply'] = _MAGNETREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MagnetRequest = _reflection.GeneratedProtocolMessageType('MagnetRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAGNETREQUEST,
  '__module__' : 'magnet_pb2'
  # @@protoc_insertion_point(class_scope:MagnetRequest)
  })
_sym_db.RegisterMessage(MagnetRequest)

MagnetReply = _reflection.GeneratedProtocolMessageType('MagnetReply', (_message.Message,), {
  'DESCRIPTOR' : _MAGNETREPLY,
  '__module__' : 'magnet_pb2'
  # @@protoc_insertion_point(class_scope:MagnetReply)
  })
_sym_db.RegisterMessage(MagnetReply)



_MAGNET = _descriptor.ServiceDescriptor(
  name='Magnet',
  full_name='Magnet',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=78,
  serialized_end=131,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMagnet',
    full_name='Magnet.GetMagnet',
    index=0,
    containing_service=None,
    input_type=_MAGNETREQUEST,
    output_type=_MAGNETREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAGNET)

DESCRIPTOR.services_by_name['Magnet'] = _MAGNET

# @@protoc_insertion_point(module_scope)
